node_js:
- "0.10"
language: node_js
tiddlyspace_username:
  secure: ZM2RSwbykNA5FQaqi1mvMONBOhuWX8FFVvK6wMQ5LbDXne1/880uZxbPbaUPvRq+vjuotQEU3AL7o8xyKNfffvvVM3quLYxIFzZmNp9q2faDJB/bSg00gNWB5aAeqWhg9gfoo0mPzq/+MZV3NIRKns2m6JRHfoxzR9PLy/LM19c=
tiddlyspace_password:
  secure: Kd4qbeNHOKWEf75oKIlTK6qoN/0IfTBIHa+fpxAZGZPRdPQ/tuFonLOyLcoGu2jG4WF1yKhYA1ms28RznwouFhVjvtWkS2QhBGqbAwabCHrzGtsCBBygdvDVo0OrPl/VFrmmbFlCvC5p24wvc2v4mD8/0jqJb54BXNQXLYyLO0s=
before_script: npm install -g istanbul && npm install -g mocha
script: make test-cov
after_success:
  - make coveralls
  - make auth