node_js: 
- "0.10"
language: node_js
env: 
  global: 
  matrix: 
  - secure: XuI+q48xC4Rv4uEqXTMFd6Ok8E03iKU8Pae2kWcGH3IVfb3PL+1lVqcC/zFuLL7k4yB0QWSnGb8OLQYbuyFSd8ykTwdDMLWIEfXEOnzHs0xuuXo46lfRSicaisRg8tZau/coR5eq0RHfPzhe4mS6Tju37D/3+8vVXiL59DDgOCU=
  - secure: NGuRML6rtOsQVjVQGTmlYGRExc+ug/SVtYHWwKaEyA78ZzwyCJChIHocrTzNxMzKUX6ALGjUEOnRXrbKqvDhtZcEmsk/4qpkpRLxGkKaZ6md9tiHiZo1vYlxgkgCbJaiP7wA5nUJVqP1RQHAqCQzdSZNt8pUdbMrkLmHWCrQCzg=
before_script: 
- npm install -g istanbul
- npm install -g mocha
- pip install -U tsapp
script: make test-cov
after_success: 
- make coveralls
- make auth
